name: CI/CD pipeline to Azure VM

on:
  pull_request:
    branches:
      - main
    types:
      - opened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  connect_to_vm:
    runs-on: ubuntu-latest
    env: 
      VM_SECRET: ${{ secrets.VM_SECRET }}
      VM_ADDRESS: ${{ secrets.VM_ADDRESS }}
    steps:
      - uses: actions/checkout@v4
      - name: Get SSH key from secrets
        run: |
          ssh -i $env:VM_SECRET $env:VM_ADDRESS &&
          yes &&
          touch test.txt
          
        
    
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Node Modules
  #       run: npm ci
