name: CI/CD pipeline to Azure VM

on:
  pull_request:
    branches:
      - main
    types:
      - opened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  connect_to_vm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get SSH key from secrets
        env: 
          VM_SECRET: ${{ secrets.VM_SECRET }}
          VM_ADDRESS: ${{ secrets.VM_ADDRESS }}
        run: |
          echo "$VM_SECRET" > id_rsa
          chmod 600 id_rsa
          ssh -i id_rsa $VM_ADDRESS
          touch test.txt
          
        
    
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Node Modules
  #       run: npm ci
