name: CI/CD pipeline to Azure VM

on:
  pull_request:
    branches:
      - main
    types:
      - opened

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  connect-azure-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Log in to Azure
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install SSH client
      run: sudo apt-get install -y ssh

    - name: Add SSH key
      run: echo "${{ secrets.VM_SECRET }}" > mykey && chmod 600 mykey

    - name: Connect to Azure VM and execute commands
      run: |
        ssh -i mykey -o StrictHostKeyChecking=no ${{ secrets.VM_ADDERSS }} "echo 'Connected to Azure VM!'"
          
        
    
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Node Modules
  #       run: npm ci
