name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          **/!(node_modules)/**

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: .

    - name: Azure VM deployment
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure VM
      uses: azure/webapps-deploy@v2
      with:
        app-name: github-actions
        publish-profile: ${{ secrets.AZURE_VM_PUBLISH_PROFILE }}
        remote-script: |
          cd /path/to/your/app
          git pull
          npm ci
          npm run start
